{% set name = "snowflake-sqlalchemy" %}
{% set version = "1.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 79191ec3febfb32bcffecd66f2a7dd561bd571345ea4bccbf41cc1fb5c0682ff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - importlib-metadata
    - snowflake-connector-python <4.0.0
    - sqlalchemy >=1.4.19,<2.0.0

test:
  imports:
    - snowflake.sqlalchemy
  requires:
    - pip
  commands:
    - python -m pip check

about:
  home: https://github.com/snowflakedb/snowflake-sqlalchemy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Snowflake SQLAlchemy Dialect

extra:
  recipe-maintainers:
    - xhochy
    - xylar
