{% set name = "snowflake-sqlalchemy" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bcf18b84f5a5c3be71703a25563f32d802f9c7be687f9c89fbd8e749f8392705

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - importlib-metadata
    - snowflake-connector-python
    - sqlalchemy

test:
  imports:
    - snowflake.sqlalchemy
  requires:
    - pip
  commands:
    - python -m pip check

about:
  home: https://github.com/snowflakedb/snowflake-sqlalchemy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Snowflake SQLAlchemy Dialect

extra:
  recipe-maintainers:
    - xhochy
    - xylar
