{% set name = "snowflake-sqlalchemy" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/12/2b/f23dc1e8187275d970c7c4461683f8ac17ba07b3a04127f3f52793d6a4b8/snowflake_sqlalchemy-{{ version }}.tar.gz
  sha256: a06b78d8b83ca74318e6fbb2982b9fbd9ce99e202f502c1f6af7ba69d05da1f5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - snowflake-connector-python <4.0.0
    - sqlalchemy >=1.4.19

test:
  imports:
    - snowflake.sqlalchemy
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - python -m pip check

about:
  home: https://github.com/snowflakedb/snowflake-sqlalchemy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Snowflake SQLAlchemy Dialect

extra:
  recipe-maintainers:
    - xhochy
    - xylar
