schema_version: 1

context:
  name: snowflake-sqlalchemy
  version: "1.10.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/snowflake_sqlalchemy-${{ version }}.tar.gz
  sha256: 5a39e4e7c560441d6c1439331228b0db80d9cfa1ef8f68cb873740f4c63e2813

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - snowflake-connector-python <5.0.0
    - sqlalchemy >=1.4.19

tests:
  - python:
      imports:
        - snowflake.sqlalchemy
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Snowflake SQLAlchemy Dialect
  homepage: https://github.com/snowflakedb/snowflake-sqlalchemy

extra:
  recipe-maintainers:
    - xhochy
    - xylar
